---
# Test framework: "xcuitest" or "espresso"
testFramework: espresso
 
# Path to the app's .ipa or .app.
app: app-debug.apk

# Path to the test runner app's .ipa or .app.
#test: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
test: app-debug-test.apk
 
# Path where XML test reports will be saved.
xmlFolder: ./

# Define a list of devices on which the tests should be executed.
devices:
 
- datacenter: US
  deviceNameQuery: Samsung.*
  envs:
  - key: annotation
    value: com.saucelabs.app.ExampleAnnotation

- datacenter: US
  deviceNameQuery: Google.*
  envs:
  - key: class
    value: com.saucelabs.app.TestClass

- datacenter: US
  deviceNameQuery: Amazon.*
  envs:
  - key: package
    value: com.saucelabs.app

- datacenter: US
  deviceNameQuery: Asus.*
  envs:
  - key: size
    value: large

