# Example 5: Parallel execution using dynamic devices
# Run two tests on separate random iPhone devices in my pool, this can be US/EU

apiVersion: v1alpha
kind: xcuitest
sauce:
  # This can be `eu-central-1` or  `us-west-1`
  region: eu-central-1
  concurrency: 10
  metadata:
    name: Testing XCUITEST Support
    tags:
      - ios
      - xcuitest
      - ex4
  build: "Sauce XCUITest Real Devices"

xcuitest:
  app: ./apps/SauceLabs.Mobile.Sample.XCUITest.App.ipa
  testApp: ./apps/SwagLabsMobileAppUITests-Runner.app

suites:
  - name: "Sauce Labs XCUITest Tests from Example 5 - testSuccessfulLogin"
    testOptions:
      class: ["SwagLabsMobileAppUITests.LoginTests/testSuccessfulLogin"]
    devices:
      # Run on whatever iPhone device is available
      - name: "iPhone.*"
        platformVersion: "14.6"
  - name: "Sauce Labs XCUITest Tests from Example 5 - testSuccessfulLogin"
    testOptions:
      class: ["SwagLabsMobileAppUITests.LoginTests/testSuccessfulLogin"]
    devices:
      # Run on whatever iPhone device is available
      - name: "iPhone.*"
        platformVersion: "13.7"

artifacts:
  download:
    when: always
    match:
      - "*.junit.xml"
    directory: ./reports/
